// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CheckAllController from "./check_all_controller"
application.register("check-all", CheckAllController)

import ComboboxController from "./combobox_controller"
application.register("combobox", ComboboxController)

import ContextMenuController from "./context_menu_controller"
application.register("context-menu", ContextMenuController)

import DialogController from "./dialog_controller"
application.register("dialog", DialogController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import DynamicUnitsController from "./dynamic_units_controller"
application.register("dynamic-units", DynamicUnitsController)

import ElementRemovalController from "./element_removal_controller"
application.register("element-removal", ElementRemovalController)

import FormController from "./form_controller"
application.register("form", FormController)

import HotkeysController from "./hotkeys_controller"
application.register("hotkeys", HotkeysController)

import LinkController from "./link_controller"
application.register("link", LinkController)

import MenuController from "./menu_controller"
application.register("menu", MenuController)

import MmToMController from "./mm_to_m_controller"
application.register("mm-to-m", MmToMController)

import NavigationController from "./navigation_controller"
application.register("navigation", NavigationController)

import PopoverController from "./popover_controller"
application.register("popover", PopoverController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)

import TurboConfirmController from "./turbo_confirm_controller"
application.register("turbo-confirm", TurboConfirmController)

import PhotoUploaderController from "./photo_uploader_controller"
application.register("photo-uploader", PhotoUploaderController)