// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CheckAllController from "./check_all_controller"
application.register("check-all", CheckAllController)

import ComboboxController from "./combobox_controller"
application.register("combobox", ComboboxController)

import DialogController from "./dialog_controller"
application.register("dialog", DialogController)

import DynamicUnitsController from "./dynamic_units_controller"
application.register("dynamic-units", DynamicUnitsController)

import ElementRemovalController from "./element_removal_controller"
application.register("element-removal", ElementRemovalController)

import FormController from "./form_controller"
application.register("form", FormController)

import NavigationController from "./navigation_controller"
application.register("navigation", NavigationController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)

import TurboConfirmController from "./turbo_confirm_controller"
application.register("turbo-confirm", TurboConfirmController)
